spring:
  # session 세팅
  session:
    timeout: 3600

  # mysql 세팅
  datasource:
    url: jdbc:mysql://db:3306/firstcome_system
    username: docker
    password: docker1234
    driver-class-name: com.mysql.cj.jdbc.Driver

  # redis 세팅
  data:
    redis:
      host: cache
      port: 6379

  # jpa 세팅
  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false

  # flyway 세팅
  flyway:
    enabled: true
    baseline-on-migrate: true
    clean-on-validation-error: true
    clean-disabled: false
    locations: classpath:db/migration

  sql:
    init:
      mode: always

  # Json 매핑을 위한 전역 설정
  jackson:
    property-naming-strategy: SNAKE_CASE

  # detools 전역 세팅
  devtools:
    restart:
      enabled: true

#Swagger 세팅
springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    operations-sorter: method
    tags-sorter: alpha
    path: /swagger
    disable-swagger-default-url: true
    doc-expansion: list
  default-consumes-media-type: application/json
  default-produces-media-type: application/json

#암/복호화를 위한 키
encryption:
  key: "0123456789abcdef"
  salt: "0123456789abcdef"

# 시큐리티 설정
security:
  public-urls:
    # 스웨거를 사용하기 위한 public url
    - "/swagger-ui/**"
    - "/api-docs/**"
    - "/swagger-resources/**"
    - "/api/health/**"
    # 상품 조회 및 회원 가입, 로그인은 열려야 된다.
    - "/api/product/**"
    - "/api/member/signup"
    - "/api/auth/login"