server:
  port: 8000

spring:
  application:
    name: gateway-service
  data:
    redis:
      host: localhost
      port: 6379
      database: 0
      timeout: 60000
      connect-timeout: 3000

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka

logging:
  level:
    com.hyunjin.gateway: DEBUG