server:
  port: 8000

spring:
  application:
    name: gateway-service

  data:
    redis:
      host: localhost
      port: 6379
      database: 0
      timeout: 60000
      connect-timeout: 3000

  cloud:
    gateway:
      globalcors:
        cors-configurations:
          '[/**]':
            allowedOrigins: "*"
            allowedMethods:
              - GET
              - POST
              - PUT
              - DELETE
              - OPTIONS
            allowedHeaders: "*"
            maxAge: 3600

  session: # 추가: 세션 관련 설정
    cookie:
      name: SESSION
    timeout: 1800  # 30분

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka

logging:
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss.SSS} [%thread] [%X{correlationId}] %-5level %logger{36} - %msg%n"
  level:
    com.hyunjin.gateway: info

gateway:
  security:
    public-paths:
      - "/api/v1/auth/login"    # 로그인
      - "/api/v1/auth/logout"   # 로그아웃
      - "/api/v1/member/signup" # 회원가입
      - "/api/v1/product/**"    # 상품 조회