-- V6__Insert_member_dummy_data.sql
INSERT INTO member (name,
                    password,
                    email,
                    phone,
                    address,
                    created_at,
                    updated_at,
                    last_password_updated)
VALUES ('홍길동',
        'password123!',
        'hong@gmail.com',
        '010-1234-5678',
        '서울시 강남구 테헤란로 123',
        CURRENT_TIMESTAMP(6),
        NULL,
        CURRENT_TIMESTAMP(6)),
       ('홍길동',
        'password123!',
        'hongchange@gmail.com',
        '010-1234-5678',
        '서울시 강남구 테헤란로 123',
        CURRENT_TIMESTAMP(6),
        NULL,
        CURRENT_TIMESTAMP(6));